window.$ = window.jquery = window.Jquery = window.jQuery = require("jquery");
window.Popper = require("@popperjs/core").default;
require("./bootstrap.min");
require("./jquery.meanmenu");
require("./jquery.appear.min");
require("./odometer.min");
require("./owl.carousel.min");
require("./jquery.magnific-popup.min");
require("./jquery.nice-select.min");
require("./imagelightbox.min");
require("./jquery.ajaxchimp.min");
require("./form-validator.min");
require("./contact-form-script");
require("./main");